# Generated by Django 2.0.6 on 2018-06-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
