# Generated by Django 2.0.6 on 2018-06-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180607_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereview',
            old_name='movie_review',
            new_name='reviewer',
        ),
    ]
